name: adult_gemini
description: "Sevak Shri Mehandipur Balaji App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # कोटलिन प्रोजेक्ट के लिए ये वर्जन सबसे स्थिर (Stable) हैं
  meta: 1.17.0
  vector_math: 2.1.4
  cupertino_icons: ^1.0.9
  battery_plus: ^7.0.0
  flutter_inappwebview: ^6.0.0
  async: ^2.11.0
  clock: ^1.1.1
  collection: ^1.18.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # इसे 0.7.10 पर ही रखना ताकि कोटलिन बिल्ड न रुके
  test_api: 0.7.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/database/panchang.db
