buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // यह लाइन 'com.android.application' को ढूंढने में मदद करेगी
        classpath 'com.android.tools.build:gradle:8.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.22"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// इसके नीचे कुछ नहीं होना चाहिए! सारा android { } वाला कोड अंदर वाली फाइल में रहेगा।
rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
