buildscript {
    ext.kotlin_version = '1.9.22' // इसे बढ़ाकर 1.9.22 कर दिया है
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        // Gradle का वर्ज़न 8.2.1 ताकि परमिशन वाला एरर खत्म हो
        classpath 'com.android.tools.build:gradle:8.2.1' 
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
