-ignorewarnings
-keep class android.window.** { *; }
-dontwarn android.window.**
-keep class ** { *; }
-dontwarn **
-dontminify
-dontshrink
-dontoptimize
-dontwarn **
-keep class ** { *; }
-keep class com.pichillilorenzo.flutter_inappwebview.** { *; }
-keep class com.tekartik.sqflite.** { *; }
-dontwarn io.flutter.embedding.**
