name: Build Balaji APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
      - run: flutter pub get
      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons
        env:
          FLUTTER_ROOT: ${{ env.FLUTTER_HOME }}
      - uses: actions/upload-artifact@v3
        with:
          name: balaji-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
