name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# 🚀 यहाँ से चेतावनी खत्म होगी
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # लेटेस्ट वर्जन
      
      - name: Set up Java
        uses: actions/setup-java@v4 # लेटेस्ट वर्जन
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          cache: true

      - name: Build APK
        run: |
          flutter clean
          flutter pub get
          # बिना श्रिंकिंग के बिल्ड ताकि R8 एरर न आए
          flutter build apk --release --target-platform android-arm64 --no-shrink

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Balaji-App-Final-No-Warnings
          path: build/app/outputs/flutter-apk/app-release.apk
